title: Chloe Tibets
description: 3D Artist
google_analytics:
show_downloads: true
theme: jekyll-theme-midnight

twitter_username: an_example
artstation_username: an_example
some_other_username: an_example

gems:
  - jekyll-mentions
