title: Chloe Tibets
description: 3D Artist / Illustrator
google_analytics:
show_downloads: true
theme: jekyll-theme-midnight

twitter_username: TibsIn3D
artstation_username: cmtibets
some_other_username: an_example

gems:
  - jekyll-mentions
